/* SoVi Living Lab — content data.
   Edit LEED points, college text, and the gold-path targets here.
   This file must load BEFORE app.js. */

const credits = [
  { code:"IP", name:"Integrative Process", earned:1, max:1,
    tags:["Construction Management","Digital Media Design","Entrepreneurship"],
    hook:"Why do green buildings work best when every trade is in the room from day one?",
    lesson:"Students trace how an early decision, say, orienting the hall to cut cooling load, ripples through structural, mechanical, and budget choices. It is a live case study in integrated project delivery, the same mindset the design-build method runs on." },
  { code:"LT", name:"Location & Transportation", earned:7, max:16,
    tags:["Civil Engineering","Environmental Studies"],
    hook:"What does it cost the planet to get 535 students to and from this building?",
    lesson:"Students map walkability, transit access, and bike infrastructure around the hall, then model how site location changes a building's lifetime carbon before a single wall goes up." },
  { code:"SS", name:"Sustainable Sites", earned:6, max:10,
    tags:["Environmental Studies","Civil Engineering","Environmental Geology"],
    hook:"How does a building sit on land that is half preserved Florida wetland?",
    lesson:"Using FGCU's own restored-nature campus as context, students study heat-island reduction, open space, and how construction disturbance is kept off sensitive ground." },
  { code:"WE", name:"Water Efficiency", earned:8, max:11,
    tags:["Environmental Studies","Environmental Engineering","Marine Science"],
    hook:"How low can a 535-bed hall push its water use, and where does the rain end up?",
    lesson:"Students compare fixture flow rates against baseline models, then follow stormwater from roof to retention and onto the campus watershed The Water School already studies. The building becomes a metered field site." },
  { code:"EA", name:"Energy & Atmosphere", earned:11, max:33,
    tags:["Environmental Engineering","Construction Management","Finance"],
    hook:"Which energy upgrades pay for themselves, and which are worth doing anyway?",
    lesson:"The biggest category becomes a two-sided problem: engineering students model envelope and HVAC performance, while business students run the life-cycle cost and payback on each measure, including the 72-hour resilience target." },
  { code:"MR", name:"Materials & Resources", earned:5, max:13,
    tags:["Construction Management","Civil Engineering","Supply Chain Management"],
    hook:"What is this building actually made of, and where did it come from?",
    lesson:"Students read real material submittals, trace embodied carbon and sourcing, and weigh construction-waste diversion against cost. Materials science meets the realities of a job-site." },
  { code:"EQ", name:"Indoor Environmental Quality", earned:8, max:16,
    tags:["Health Science","Public Health","Environmental Engineering"],
    hook:"What makes the air, light, and acoustics inside a dorm good to live and study in?",
    lesson:"Students investigate ventilation rates, daylighting, low-emission materials, and acoustic design, connecting building decisions to student health and academic performance." },
  { code:"IN", name:"Innovation", earned:4, max:6,
    tags:["Entrepreneurship","Software Engineering","Digital Media Design"],
    hook:"What could this building do that no checklist asked for?",
    lesson:"An open brief: students propose a credit-worthy innovation, from a novel sensor program to a behavior-change campaign for residents, and pitch it as a venture with costs and impact." },
  { code:"RP", name:"Regional Priority", earned:4, max:4,
    tags:["Environmental Studies","Marine Science","Civil Engineering"],
    hook:"What matters most for a green building specifically in Southwest Florida?",
    lesson:"Students examine why LEED weights certain credits by region, studying hurricane resilience, heat, and water issues that are particular to this coast rather than generic to the country." }
];

const colleges = [
  { name:"U.A. Whitaker College of Engineering", color:"#009366", codes:["SS","EA","WE","MR"],
    majors:"Civil · Environmental · Construction Mgmt · Bioengineering · Software · Computer Science",
    text:"The hall is a structural, energy, and water problem to model against real field conditions, not a textbook.",
    wayin:"This is the college that builds. Construction Management students already train on an open-air worksite lab and a virtual-construction lab on campus, so the hall gives them an actual project to plan, sequence, and cost. Civil and Environmental students model its energy, water, and material systems against real field data.",
    projects:["Build a 4D construction sequence for the hall in the virtual-construction lab and check it against the real build log.","Model the envelope and HVAC, then propose the package that hits the LEED energy target.","Audit material submittals for embodied carbon and waste diversion."] },
  { name:"The Water School", color:"#1F8FB0", codes:["WE","SS","RP"],
    majors:"Environmental Studies · Marine Science · Environmental Geology",
    text:"The building and its stormwater become a metered field site, feeding the watershed the school already studies.",
    wayin:"The Water School already treats the campus as a field site for studying the whole watershed, from rainfall down to the Gulf. The hall plugs straight into that model as a new, metered source feeding the same waters students track toward Estero Bay and the Caloosahatchee.",
    projects:["Meter the hall’s stormwater and trace it through campus retention toward the bay.","Compare the hall’s potable water use to baseline and study runoff nutrient load on seagrass.","Map the footprint against preserved wetland and assess the site-disturbance choices."] },
  { name:"Lutgert College of Business", color:"#004685", codes:["EA","MR","IN"],
    majors:"Finance · Management · Supply Chain · Analytics · Economics",
    text:"Life-cycle cost, procurement, payback, and the financial case for building green as a real spreadsheet.",
    wayin:"A building near 130 million dollars is a live finance and supply-chain case. Through the Lucas Institute for real estate development and the Center for Supply Chain Excellence, students can run the development math, the procurement chain, and the payback on every green upgrade.",
    projects:["Build the life-cycle cost and payback model for the energy package.","Map the material supply chain and weigh local sourcing against cost and embodied carbon.","Write the financial case for building to LEED rather than to code."] },
  { name:"Daveler & Kauanui School of Entrepreneurship", color:"#B58BD1", codes:["IN"],
    majors:"Entrepreneurship · Digital Media Design",
    text:"Pitch a credit-worthy innovation as a venture, and tell the building’s story to the public.",
    wayin:"Students here prototype in a makerspace and pitch through the Runway incubator. The hall’s open Innovation credit is a standing brief: invent something the checklist never asked for, build it, and pitch it as a venture.",
    projects:["Prototype a resident energy or water behavior idea in the makerspace and pitch it through Runway.","Design the hall’s public-facing story and brand as a digital media project.","Propose a credit-worthy innovation and model its cost and impact as a startup."] },
  { name:"Marieb College of Health & Human Services", color:"#E0857A", codes:["EQ"],
    majors:"Public Health · Health Science · Social Work · Exercise Science",
    text:"How indoor air, daylight, acoustics, and density shape the wellbeing of 535 residents.",
    wayin:"Public Health here already studies environmental health and how the built environment shapes wellbeing. The hall is a controlled case in how air, light, acoustics, and density affect 535 students who live and study inside it.",
    projects:["Study ventilation, daylight, and acoustics in the hall and link them to resident health and sleep.","Survey residents on wellbeing and density, then tie findings back to design choices.","Assess the indoor environment against the LEED health credits and recommend fixes."] },
  { name:"College of Arts & Sciences", color:"#CC7A22", codes:["EQ","IN","RP"],
    majors:"Communication · Journalism · Biology · Chemistry · Physics · Psychology · Art",
    text:"Document the build, study the chemistry and physics underneath it, and read how residents actually behave.",
    wayin:"This college reads the building from every side: the chemistry and physics of its materials and energy, the psychology of how residents behave, and the journalism that documents the build. Its Climate Change and Community Resilience programs, plus WGCU Public Media, give it a regional lens.",
    projects:["Document the build as a long-form journalism or WGCU media project.","Test the chemistry and physics behind the building’s material and energy claims.","Study resident behavior through a psychology lens, from occupancy to energy habits."] },
  { name:"College of Education", color:"#5FA86B", codes:["IP"],
    majors:"Elementary · Secondary · Special Education",
    text:"Turn the finished building into K-12 outreach lessons and study how people learn from a real place.",
    wayin:"Through the Whitaker Center for STEM Education, a joint effort with Arts & Sciences, FGCU already turns real research into K-12 lessons. The finished hall becomes a field site future teachers use to build inquiry-based STEM units, and a case study in how people learn from a real place.",
    projects:["Turn the hall’s sustainability story into a K-12 STEM unit through the Whitaker Center.","Design an inquiry lesson where pupils measure the building and draw conclusions.","Study the integrated design process itself as a model of collaborative learning."] }
];

const leedNames={IP:"Integrative Process",LT:"Location & Transportation",SS:"Sustainable Sites",WE:"Water Efficiency",EA:"Energy & Atmosphere",MR:"Materials & Resources",EQ:"Indoor Environmental Quality",IN:"Innovation",RP:"Regional Priority"};